"""Agent proxy service: launch, SSE relay + billing, approval/stop passthrough (ADR-045/047).

Owns the proxy logic so the router stays thin and the flow is unit-testable with a mocked Hermes
instance (respx/httpx) and a mocked ``HermesInstanceManager``. Instance lifecycle and the
``API_SERVER_KEY`` are owned by ``hermes_runtime`` (ADR-046); the decrypted key lives only in the
``InstanceEndpoint`` returned by ``ensure_running`` and is never logged or relayed to the client.

SSE wire format (Hermes external contract): ``event: <name>\\ndata: <json>\\n\\n``. The relay
forwards every event byte-for-event to the client and, on the terminal ``run.completed`` carrying
``usage``, debits the wallet exactly once (idempotency by ``runId``, ADR-047 §4).
"""

from __future__ import annotations

import asyncio
import datetime
import json
import logging
import time
import uuid
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from typing import Any, Literal

import httpx
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncSession

from app.agent_proxy.billing import usage_to_credits
from app.agent_proxy.runs_repo import AgentRunsRepository
from app.agent_proxy.snapshots_repo import AgentRunSnapshotsRepository, SnapshotUpsertResult
from app.audit.service import (
    EVENT_BILLING_DEBIT_INSUFFICIENT,
    AuditEvent,
    AuditService,
)
from app.config import Settings
from app.errors import (
    InsufficientCreditsError,
    NotFoundError,
    ResumeInProgressError,
    RunNotResumableError,
    SessionExpiredError,
    UpstreamError,
)
from app.hermes_runtime.manager import HermesInstanceManager, InstanceEndpoint
from app.policy.engine import Decision, Mode, evaluate
from app.policy.loader import load_policy_state
from app.wallet.service import WalletService

logger = logging.getLogger("app.agent_proxy.service")

# audit eventType for an agent run (audit catalog; agent-proxy/05-events.md). billing_debit is
# recorded by WalletService.consume itself; this marks the run lifecycle.
EVENT_AGENT_RUN = "agent_run"

# Terminal SSE event name that triggers billing (Hermes external contract, agent-proxy/05-events).
_EVENT_RUN_COMPLETED = "run.completed"
# ADR-066 §3: terminal failure. No debit (no usage) — but it DOES flush the snapshot and record
# agent_runs.status='failed', which before ADR-066 was never written (a crashed run stayed
# 'running' forever).
_EVENT_RUN_FAILED = "run.failed"
# ADR-066 §6: the run is waiting for the user to answer an approval request. Persisted so the
# derived client status waiting_approval survives an SSE drop / app kill.
_EVENT_APPROVAL_REQUEST = "approval.request"
# ADR-064 §7: per-LLM-call usage event emitted inside the Hermes tool-loop (image patch). Carries
# cumulative_input_tokens/cumulative_output_tokens (billing source) + step_index (per-step key).
_EVENT_USAGE_DELTA = "usage.delta"
# ADR-064 §3: assistant text delta and tool events buffered locally to build the run.paused body.
_EVENT_MESSAGE_DELTA = "message.delta"
_TOOL_EVENT_PREFIX = "tool."
# ADR-064 §3: synthetic terminal event generated by the control plane (NOT Hermes) on pause.
_EVENT_RUN_PAUSED = "run.paused"
# ADR-064 §3: pause reason when the wallet balance is exhausted mid-run.
_REASON_CREDITS_EXHAUSTED = "credits_exhausted"

# Block reasons surfaced as 200 {status:blocked} for the agent path (credits-branch only, ADR-047
# §3): the agent contour never runs in byok mode on MVP, so only these can occur. debt_outstanding
# (ADR-051 §4) is included UNCONDITIONALLY (NOT gated by the flag): the default
# AGENT_DEBT_RECONCILE_ENABLED=true makes it reachable, so it must be a valid member of the
# achievable set to avoid a false "unexpected reason" log (agent-proxy/02-api-contracts.md
# needs_code_sync). The flag gates EMISSION (whether the debt check runs), not enum membership.
_AGENT_BLOCK_REASONS = frozenset(
    {"credits_empty", "subscription_expired", "trial_used", "debt_outstanding"}
)
# Block reason for an unsettled agent-run debt (ADR-051 §4).
_DEBT_OUTSTANDING = "debt_outstanding"


@dataclass(frozen=True)
class RunLaunchResult:
    """Outcome of ``POST /v1/agent/run``.

    ``blocked`` carries ``block_reason`` and no ``run_id`` / ``status``; an allowed launch carries
    the Hermes ``run_id`` and ``status`` (queued|running) and no ``block_reason``.
    """

    blocked: bool
    block_reason: str | None = None
    run_id: str | None = None
    status: str | None = None


@dataclass(frozen=True)
class RunResumeResult:
    """Outcome of ``POST /v1/agent/runs/{runId}/resume`` (ADR-064 §5).

    ``blocked`` (HTTP 200) carries ``block_reason`` and no run ids (policy still blocks after the
    top-up gate). An allowed resolve (HTTP 202) carries the NEW child ``run_id`` and the
    ``continued_from`` parent id. Technical failures (404/409/502) are raised as exceptions.
    """

    blocked: bool
    block_reason: str | None = None
    run_id: str | None = None
    continued_from: str | None = None


# Client-facing run status of GET .../state (ADR-066 §4). Derived on read from agent_runs.status
# (+ pending approval); the DB enum agent_run_status is NOT extended. `queued` is not emitted in v1
# (forward-compat member only).
ClientRunStatus = Literal[
    "queued", "running", "waiting_approval", "paused", "completed", "failed", "stopped"
]

# Terminal DB statuses → client status. running/resumed are handled separately (they depend on the
# pending approval), `cancelled` is renamed to the client vocabulary (`POST /stop` → `stopped`).
_CLIENT_STATUS_BY_DB: dict[str, ClientRunStatus] = {
    "paused": "paused",
    "completed": "completed",
    "failed": "failed",
    "cancelled": "stopped",
}


@dataclass(frozen=True)
class RunStateView:
    """Read-only state snapshot of a run for ``GET /v1/agent/runs/{runId}/state`` (ADR-066 §5).

    Assembled from ``agent_runs`` (lifecycle: status, session, resume chain, pause reason) plus the
    optional ``agent_run_snapshots`` row (UX state: text, tool, approval, tokens). ``status`` is
    already the CLIENT-facing value (see :func:`map_client_status`).
    """

    run_id: str
    session_id: str
    status: ClientRunStatus
    result_text: str
    last_tool: str | None
    pending_approval: dict[str, Any] | None
    block_reason: str | None
    input_tokens: int
    output_tokens: int
    updated_at: datetime.datetime
    continued_from: str | None


@dataclass
class _RelayState:
    """Relay-local accumulation for the run snapshot and the synthetic ``run.paused`` body.

    Lives for one ``stream_events`` call. Accumulated ALWAYS — outside the
    ``agent_incremental_billing_enabled`` branch (ADR-066 §6): the snapshot is written regardless of
    the billing flag, and with the flag OFF the token counters are filled from ``run.completed``
    instead of ``usage.delta``.
    """

    # message.delta pieces. COLLAPSED into a single head-truncated element on every flush, so the
    # buffer is bounded by AGENT_STATE_RESULT_TEXT_MAX_CHARS regardless of run length and the join
    # never walks an ever-growing list. Consequence: the run.paused `output` is bounded by the same
    # cap — acceptable, that body is a convenience snapshot, not an authoritative transcript.
    partial_text: list[str] = field(default_factory=list)
    # Raw tool.* payloads — the `steps` array of the synthetic run.paused body (ADR-064 §3).
    # Bounded by the number of tool calls of a single run (units-to-hundreds), not by stream volume.
    steps: list[dict[str, Any]] = field(default_factory=list)
    last_tool: str | None = None
    # The relay's belief about a pending approval. Asserted to the DB only on immediate flushes —
    # the client can answer POST …/approval out of band, so a throttled text flush must not
    # resurrect a stale value (see _flush_snapshot).
    pending_approval: dict[str, Any] | None = None
    # Cumulative token counters (monotonic; also the run.paused usage anchors).
    input_tokens: int = 0
    output_tokens: int = 0
    # time.monotonic() of the last DB flush; 0.0 => the first delta flushes immediately.
    last_flush_at: float = 0.0
    # One-shot latches: each anomaly is logged ONCE per relay (on transition), not per flush —
    # a frozen text or a tenancy collision persists for the rest of the stream and would otherwise
    # emit a line every few seconds for the whole run.
    tenancy_skip_logged: bool = False
    text_frozen_logged: bool = False


def map_client_status(db_status: str, *, has_pending_approval: bool) -> ClientRunStatus:
    """Map ``agent_runs.status`` (+ approval presence) to the client status (ADR-066 §4). Pure.

    ``running``/``resumed`` → ``running``, or ``waiting_approval`` when an approval is pending —
    a DERIVED status computed on read, deliberately NOT a value of the ``agent_run_status`` enum
    (a DB enum migration is more expensive than a mapping, and duplicating the status into the
    snapshot would create a second source of truth). ``resumed`` belongs to the PARENT row after a
    resume — the work continues in the child run whose id ``/resume`` returned — so it maps to
    ``running`` too. ``cancelled`` → ``stopped`` (the client vocabulary follows ``POST …/stop``;
    the server enum value is not renamed). ``queued`` is never emitted in v1 (forward-compat only).
    """
    if db_status in ("running", "resumed"):
        return "waiting_approval" if has_pending_approval else "running"
    # paused/completed/failed pass through, cancelled becomes stopped. An unknown value can only
    # come from a future enum member; degrade to `running` rather than emit an off-contract status.
    return _CLIENT_STATUS_BY_DB.get(db_status, "running")


class AgentProxyService:
    """Proxies the client agent contour to the user's Hermes instance (ADR-045)."""

    def __init__(
        self,
        *,
        session: AsyncSession,
        manager: HermesInstanceManager,
        wallet: WalletService,
        audit: AuditService,
        settings: Settings,
        runs: AgentRunsRepository,
        snapshots: AgentRunSnapshotsRepository,
    ) -> None:
        self._session = session
        self._manager = manager
        self._wallet = wallet
        self._audit = audit
        self._settings = settings
        self._runs_repo = runs
        self._snapshots_repo = snapshots

    # --- run launch -------------------------------------------------------------------------

    async def run(
        self,
        *,
        user_id: uuid.UUID,
        message: str,
        session_id: str | None,
        model: str | None,
    ) -> RunLaunchResult:
        """Policy-gate → ensure_running → proxy ``POST /v1/runs`` (ADR-045 §2, ADR-047 §3).

        Order is strict: (1) policy evaluate in the credits branch — blocked stops here WITHOUT
        waking the container or debiting (200 blocked, ADR-004); (2) ``ensure_running`` resolves
        the user's instance endpoint + bearer key; (3) proxy the launch with the mapped body.
        Any upstream/instance failure surfaces as 502 (UpstreamError), never as 200 blocked.
        """
        # (1) Policy gate (credits branch; agent path has no byok mode on MVP, ADR-047 §3).
        state = await load_policy_state(self._session, user_id)
        decision: Decision = evaluate(state, Mode.credits)
        if not decision.allow:
            reason = decision.block_reason.value if decision.block_reason is not None else None
            await self._audit.record(
                AuditEvent(
                    user_id=user_id,
                    event_type=EVENT_AGENT_RUN,
                    payload={"phase": "blocked", "blockReason": reason},
                )
            )
            # Defensive: only the credits-branch reasons are expected here.
            if reason not in _AGENT_BLOCK_REASONS:
                logger.warning("agent run blocked with unexpected reason=%s", reason)
            return RunLaunchResult(blocked=True, block_reason=reason)

        # (1b) Debt-gate (ADR-051 §4): an unsettled agent-run debt blocks a NEW run BEFORE waking
        # the container (200 blocked, ADR-004). Reachable only on the agent path, only when
        # AGENT_DEBT_RECONCILE_ENABLED (the EMISSION gate). Cleared by clawback on the next grant.
        if self._settings.agent_debt_reconcile_enabled:
            debt = await self._wallet.current_debt(user_id)
            if debt > 0:
                await self._audit.record(
                    AuditEvent(
                        user_id=user_id,
                        event_type=EVENT_AGENT_RUN,
                        payload={
                            "phase": "blocked",
                            "blockReason": _DEBT_OUTSTANDING,
                            "debt": debt,
                        },
                    )
                )
                return RunLaunchResult(blocked=True, block_reason=_DEBT_OUTSTANDING)

        # (2) Resolve (provision/wake) the user's Hermes instance.
        endpoint = await self._manager.ensure_running(user_id)

        # (3) Proxy the launch. Map iOS body → Hermes body (ADR-045 §4). ADR-064 §5: compute a
        # STABLE session_id (client-supplied or a fresh uuid4) and pass it to Hermes so the whole
        # continuation chain shares one session; resume resolves it from the paused run_id (the
        # client never has to store it).
        effective_session_id = session_id or str(uuid.uuid4())
        hermes_body: dict[str, Any] = {"input": message, "session_id": effective_session_id}
        if model is not None:
            hermes_body["model"] = model

        run_id, status = await self._launch_run(endpoint, hermes_body)
        # ADR-066 §3: the ROOT agent_runs row (continued_from NULL) is created ALWAYS — the row is
        # an unconditional LIFECYCLE record, no longer gated by agent_incremental_billing_enabled
        # (with the flag OFF the default configuration used to store no agent runs at all, so
        # neither /state nor any run history existed). The flag keeps gating only the BILLING
        # fields/operations. Committed by the request session_scope teardown (run() is a plain
        # handler, like the audit rows below).
        await self._runs_repo.create_running(
            run_id, user_id, effective_session_id, model, status="running"
        )
        await self._audit.record(
            AuditEvent(
                user_id=user_id,
                event_type=EVENT_AGENT_RUN,
                payload={"phase": "launched", "runId": run_id, "status": status},
            )
        )
        return RunLaunchResult(blocked=False, run_id=run_id, status=status)

    async def _launch_run(
        self, endpoint: InstanceEndpoint, body: dict[str, Any]
    ) -> tuple[str, str]:
        """POST {base}/v1/runs with the instance bearer; return (run_id, status). 502 on failure.

        ADR-062 §2 connect-only retry (defense-in-depth for the wake-gap / a transient connect
        blip): on a CONNECT-phase transport error — the request is guaranteed NOT to have reached
        the server — retry up to ``hermes_launch_retry_attempts`` TOTAL attempts with a fixed
        backoff. POST /v1/runs is NOT idempotent (no client key), so ONLY the connect phase is safe
        to retry; any post-send error (write/read/protocol) may have created a run and is re-raised
        immediately as 502 (double-run risk). A fresh ``httpx.AsyncClient`` is used per attempt.
        """
        url = f"{endpoint.base_url}/v1/runs"
        # ADR-062 §2: EXPLICIT tuple, NOT a base class. In httpx 0.28.1 ConnectTimeout is NOT a
        # subclass of ConnectError (both connect-phase, but split under
        # TimeoutException/NetworkError respectively); catching
        # TimeoutException/NetworkError/TransportError would also swallow ReadTimeout/WriteError
        # (post-send) → double-run risk. Match strictly the connect set.
        connect_errors = (httpx.ConnectError, httpx.ConnectTimeout, httpx.PoolTimeout)
        attempts = max(self._settings.hermes_launch_retry_attempts, 1)
        response: httpx.Response | None = None
        for attempt in range(1, attempts + 1):
            try:
                async with httpx.AsyncClient(
                    timeout=self._settings.hermes_proxy_timeout_seconds
                ) as client:
                    response = await client.post(
                        url, json=body, headers=self._bearer_headers(endpoint.api_key)
                    )
                break
            except httpx.HTTPError as exc:
                # Retry ONLY on a connect-phase error with attempts remaining; otherwise 502.
                if isinstance(exc, connect_errors) and attempt < attempts:
                    logger.warning(
                        "hermes run launch connect error, retrying attempt=%d/%d",
                        attempt,
                        attempts,
                    )
                    await asyncio.sleep(self._settings.hermes_launch_retry_backoff_seconds)
                    continue
                logger.warning("hermes run launch transport error")
                raise UpstreamError("hermes instance unreachable") from exc
        if response is None:  # pragma: no cover - loop always breaks on success or raises
            # Defensive: the loop breaks on success or raises on the final failed attempt.
            raise UpstreamError("hermes instance unreachable")

        if not 200 <= response.status_code < 300:
            logger.warning("hermes run launch non-2xx status=%s", response.status_code)
            raise UpstreamError("hermes run launch failed")

        try:
            payload = response.json()
        except ValueError as exc:
            raise UpstreamError("hermes run launch returned invalid body") from exc
        run_id = payload.get("run_id")
        if not isinstance(run_id, str) or not run_id:
            raise UpstreamError("hermes run launch returned no run_id")
        status = payload.get("status")
        if status not in ("queued", "running"):
            # Normalize any other/missing status to queued (the client only distinguishes
            # queued/running; both mean "accepted").
            status = "queued"
        return run_id, status

    # --- SSE relay + billing ----------------------------------------------------------------

    async def stream_events(self, *, user_id: uuid.UUID, run_id: str) -> AsyncIterator[bytes]:
        """Relay the instance SSE stream to the client; bill per-step or once (ADR-047/ADR-064).

        The run is addressed within the user's own instance (RBAC: runId is namespaced to the
        subject's instance, agent-proxy/06-rbac.md), so ``ensure_running(user_id)`` resolves it —
        a foreign run is unreachable by construction. Events are forwarded as-is.

        With ``AGENT_INCREMENTAL_BILLING_ENABLED`` (ADR-064): ``charged`` is seeded from the ledger
        (reconnect-safe), each ``usage.delta`` bills the cumulative-owed-minus-charged delta
        (self-clamping, no debt), and on balance exhaustion the run is stopped and a synthetic
        terminal ``run.paused`` is emitted (no ``run.completed`` follows). On ``run.completed`` the
        remainder (``owed_final - charged``) is finalized. Flag OFF => ``charged`` stays 0 and
        ``run.completed`` bills the full usage once (idempotency_key=run_id) — the ADR-047 behaviour
        unchanged. ``run.failed`` is forwarded without any debit (ADR-047 §4).

        ADR-066 §6 — SNAPSHOT SIDE EFFECT (independent of the billing flag): the same pass upserts
        the run state into ``agent_run_snapshots`` (text/last tool/pending approval/tokens, each
        write committed explicitly — the streaming context runs after the request-session teardown)
        and records terminal statuses in ``agent_runs`` (``completed``/``failed``, conditional).
        This is the ONLY source of ``GET /v1/agent/runs/{runId}/state``: while nobody is subscribed
        here, the snapshot of an active run does not move (a known v1 limitation — a background
        consumer is deferred, ADR-066 §8).
        """
        incremental = self._settings.agent_incremental_billing_enabled
        endpoint = await self._manager.ensure_running(user_id)
        url = f"{endpoint.base_url}/v1/runs/{run_id}/events"
        # Long-lived stream: bound connect/write, disable read timeout so a slow run is not killed.
        timeout = httpx.Timeout(
            connect=self._settings.hermes_sse_connect_timeout_seconds,
            read=None,
            write=self._settings.hermes_sse_connect_timeout_seconds,
            pool=self._settings.hermes_sse_connect_timeout_seconds,
        )
        billed = False
        # ADR-064 §6: re-seed charged from the ledger so a re-subscription after an SSE drop does
        # not re-bill already-charged steps (per-step idempotency guarantees it directly; the seed
        # avoids redundant no-op consume calls too). Post-hoc mode keeps charged == 0.
        charged = await self._wallet.charged_for_run(user_id, run_id) if incremental else 0
        # Local relay buffer: feeds BOTH the synthetic run.paused body (ADR-064 §3) and the
        # agent_run_snapshots writer (ADR-066 §6) — accumulated regardless of the billing flag.
        state = _RelayState()
        try:
            async with (
                httpx.AsyncClient(timeout=timeout) as client,
                client.stream(
                    "GET", url, headers=self._bearer_headers(endpoint.api_key)
                ) as response,
            ):
                if not 200 <= response.status_code < 300:
                    logger.warning("hermes events non-2xx status=%s", response.status_code)
                    raise UpstreamError("hermes events stream failed")
                async for block, raw in _iter_sse_blocks(response):
                    # Relay the raw bytes verbatim to the client (no re-encoding drift).
                    yield raw
                    name = _event_name(block)
                    if name == _EVENT_MESSAGE_DELTA:
                        text_piece = _extract_delta_text(block)
                        if text_piece:
                            state.partial_text.append(text_piece)
                            # Throttled: text is the only high-frequency writer (ADR-066 §6.1).
                            await self._flush_snapshot(
                                user_id=user_id, run_id=run_id, state=state, immediate=False
                            )
                    elif name is not None and name.startswith(_TOOL_EVENT_PREFIX):
                        state.steps.append(block.data)
                        tool = _extract_tool_name(block)
                        if tool:
                            state.last_tool = tool
                        # The agent moved on => any pending approval is resolved (ADR-066 §6).
                        state.pending_approval = None
                        await self._flush_snapshot(
                            user_id=user_id, run_id=run_id, state=state, immediate=True
                        )
                    elif name == _EVENT_APPROVAL_REQUEST:
                        state.pending_approval = self._build_pending_approval(block)
                        # IMMEDIATE, bypassing the throttle: a delayed write would leave the client
                        # unaware that the run is waiting for its answer (ADR-066 §6.1).
                        await self._flush_snapshot(
                            user_id=user_id, run_id=run_id, state=state, immediate=True
                        )
                    elif name == _EVENT_USAGE_DELTA:
                        # Cumulative token anchors — recorded for the snapshot even with billing
                        # OFF (a patched image may emit usage.delta regardless).
                        state.input_tokens = max(
                            state.input_tokens,
                            _as_int(block.data.get("cumulative_input_tokens")),
                        )
                        state.output_tokens = max(
                            state.output_tokens,
                            _as_int(block.data.get("cumulative_output_tokens")),
                        )
                        if incremental:
                            charged, depleted = await self._bill_step(
                                user_id=user_id, run_id=run_id, event=block, charged=charged
                            )
                            if depleted:
                                # Pause-at-zero: interrupt the run, persist paused, emit the
                                # synthetic terminal run.paused, close the stream (no
                                # run.completed).
                                yield await self._pause_run(
                                    user_id=user_id,
                                    run_id=run_id,
                                    charged=charged,
                                    state=state,
                                )
                                return
                    elif name == _EVENT_RUN_FAILED:
                        # No debit (no usage). ADR-066 §3: final flush + a CONDITIONAL failed
                        # status — before ADR-066 a crashed run stayed 'running' forever.
                        state.pending_approval = None
                        await self._flush_snapshot(
                            user_id=user_id, run_id=run_id, state=state, immediate=True
                        )
                        await self._mark_terminal(run_id, "failed")
                    elif name == _EVENT_RUN_COMPLETED:
                        # Flag OFF => there are no usage.delta events, so the snapshot token
                        # counters come from the terminal usage payload (ADR-066 §6).
                        usage = _extract_usage(block)
                        state.input_tokens = max(
                            state.input_tokens, _as_int(usage.get("input_tokens"))
                        )
                        state.output_tokens = max(
                            state.output_tokens, _as_int(usage.get("output_tokens"))
                        )
                        state.pending_approval = None
                        await self._flush_snapshot(
                            user_id=user_id, run_id=run_id, state=state, immediate=True
                        )
                        # ADR-066 §3: the lifecycle status is recorded HERE, before billing and
                        # independently of its outcome. Inside _bill_completed it would be skipped
                        # whenever an unexpected billing error hit the generic rollback branch,
                        # leaving the run 'running' forever and making /state lie indefinitely.
                        # The transition is conditional, so a replayed run.completed is a no-op.
                        await self._mark_terminal(run_id, "completed")
                        if not billed:
                            billed = await self._bill_completed(
                                user_id=user_id, run_id=run_id, event=block, charged=charged
                            )
        except httpx.HTTPError as exc:
            # A mid-stream transport drop: the client connection ends. Billing idempotency by
            # run_id (and per-step run_id:step) lets a re-subscription complete billing later
            # (ADR-045 §6, ADR-064 §6, Q-047-2).
            logger.warning("hermes events transport error (stream ended)")
            raise UpstreamError("hermes events stream error") from exc

    async def _bill_step(
        self, *, user_id: uuid.UUID, run_id: str, event: _SseEvent, charged: int
    ) -> tuple[int, bool]:
        """Bill one ``usage.delta`` (ADR-064 §1): cumulative-owed-minus-charged, self-clamping.

        Returns ``(charged, depleted)``. ``owed = usage_to_credits(cumulative_in, cumulative_out)``
        (the SAME pure function as post-hoc, so the telescoping sum of per-step charges converges
        EXACTLY to ``usage_to_credits(final)`` — no price inflation). ``want = owed - charged``;
        ``charge = min(want, balance)``. A ``charge > 0`` debits via the incremental (no-debt)
        consume path (idempotency ``run_id:step``) and commits (streaming context — the request
        session teardown already ran). ``charged`` and the agent_runs mirror advance by the ACTUAL
        credits decremented (``ConsumeResult.charged_amount`` — may be < ``charge`` if a concurrent
        chat-debit clamped the balance), so both stay consistent with the ledger (money invariant).
        ``depleted = actual < want`` signals a balance shortfall → the caller pauses. A ``charge``
        of 0 (balance already 0) skips the debit and reports depletion. An idempotent replay of the
        step is not double-counted and does not trigger a spurious pause.
        """
        data = event.data
        cumulative_in = _as_int(data.get("cumulative_input_tokens"))
        cumulative_out = _as_int(data.get("cumulative_output_tokens"))
        step_index = _as_int(data.get("step_index"))
        model = _extract_model(event)
        owed = usage_to_credits(
            input_tokens=cumulative_in,
            output_tokens=cumulative_out,
            credits_per_1k_input=self._settings.credits_per_1k_input,
            credits_per_1k_output=self._settings.credits_per_1k_output,
        )
        want = owed - charged
        if want <= 0:
            # Nothing new owed yet (cumulative unchanged / rounding): no debit, not depleted.
            return charged, False
        balance = await self._wallet.current_balance(user_id)
        charge = min(want, balance)
        actual = 0
        if charge > 0:
            meta: dict[str, Any] = {
                "source": "agent_run",
                "incremental": True,
                "runId": run_id,
                "stepIndex": step_index,
                "usage": {
                    # Per-step delta names (input_tokens/output_tokens) and the cumulative_*
                    # anchors (informational, ADR-064 §7) all survive redaction via the
                    # _USAGE_COUNT_ALLOWLIST carve-out (TD-035 closed).
                    "input_tokens": _as_int(data.get("input_tokens")),
                    "output_tokens": _as_int(data.get("output_tokens")),
                    "cumulative_input_tokens": cumulative_in,
                    "cumulative_output_tokens": cumulative_out,
                },
                "model": model,
            }
            result = await self._wallet.consume(
                user_id=user_id,
                amount=charge,
                idempotency_key=f"{run_id}:{step_index}",
                meta=meta,
            )
            if result.idempotent_replay:
                # Step already billed (reconnect / concurrent stream): the prior debit stands — do
                # not double-count and do not treat it as a fresh depletion.
                return charged, False
            # Use the ACTUAL credits decremented (may be < charge if a concurrent chat-debit clamped
            # the balance) so charged + the agent_runs mirror stay consistent with the ledger
            # (money invariant). Advance the mirror in the SAME commit as the debit — the streaming
            # context needs an explicit commit (teardown already ran).
            actual = result.charged_amount
            if actual > 0:
                await self._runs_repo.record_step(run_id, step_index, actual)
            await self._session.commit()
            charged += actual
        # Depleted when the wallet could not fully cover `want` (balance was 0, or a race clamped
        # the actual charge below want).
        depleted = actual < want
        return charged, depleted

    # --- snapshot writer (ADR-066 §6) ---------------------------------------------------------

    async def _flush_snapshot(
        self, *, user_id: uuid.UUID, run_id: str, state: _RelayState, immediate: bool
    ) -> None:
        """Persist the accumulated relay state into ``agent_run_snapshots`` (ADR-066 §6).

        ``immediate=False`` (the ``message.delta`` path) is THROTTLED to at most one write per
        ``AGENT_STATE_FLUSH_INTERVAL_SECONDS``; terminal events and ``approval.request`` pass
        ``immediate=True`` and bypass the throttle.

        ``result_text`` is truncated HEAD-preserving to ``AGENT_STATE_RESULT_TEXT_MAX_CHARS``:
        keeping the beginning keeps the prefix stable, which is what the per-column replay-guard
        (prefix-continuation check, ADR-066 §6.2) relies on. Once the cap is reached the length
        freezes, and every subsequent write submits exactly the same first N characters — incoming
        and stored values coincide in full, so both the length and the prefix condition hold and
        updates keep going through (the write is simply a no-op for that column, while tools,
        approval and tokens still advance). The full text always remains available through
        ``/events``. The joined+truncated text REPLACES the delta buffer,
        so a long run neither grows the buffer without bound nor re-joins an ever-longer list every
        few seconds; the operation is idempotent w.r.t. the value (concatenating the collapsed head
        with the following deltas yields the same head).

        ``pending_approval`` is asserted ONLY on immediate flushes. Every immediate flush is
        triggered by an event that carries authoritative approval information (``approval.request``
        sets it; ``tool.*`` and the terminal events clear it), whereas a throttled ``message.delta``
        flush knows nothing about it: the client may have answered ``POST …/approval`` out of band,
        and re-asserting the relay's cached value would resurrect a false ``waiting_approval``.

        An explicit ``commit()`` is required (streaming context: the request-session teardown has
        already run, ADR-064 pattern ``_bill_step``). A persistence failure must NEVER break the
        relay — most notably a foreign-key miss for a run started before ``agent_runs`` became an
        unconditional lifecycle row: it is rolled back and logged WITHOUT any user content.
        """
        if not immediate:
            elapsed = time.monotonic() - state.last_flush_at
            if elapsed < self._settings.agent_state_flush_interval_seconds:
                return
        result_text = "".join(state.partial_text)
        max_chars = self._settings.agent_state_result_text_max_chars
        if len(result_text) > max_chars:
            result_text = result_text[:max_chars]  # head-preserving (never the tail)
        # Collapse the buffer: bounded memory for a long run and an O(1)-sized join next time.
        state.partial_text = [result_text]
        try:
            written = await self._snapshots_repo.upsert(
                run_id=run_id,
                user_id=user_id,
                result_text=result_text,
                last_tool=state.last_tool,
                pending_approval=state.pending_approval,
                input_tokens=state.input_tokens,
                output_tokens=state.output_tokens,
                assert_pending_approval=immediate,
            )
            await self._session.commit()
            self._log_write_anomaly(
                run_id=run_id, state=state, written=written, submitted_length=len(result_text)
            )
        except SQLAlchemyError:
            # Generic log (no run text, no approval preview — this is user content, ADR-066 §5).
            logger.warning("agent run snapshot write failed run_id=%s", run_id)
            await self._session.rollback()
        # Reset the throttle window even on failure so a permanently failing write (e.g. a missing
        # agent_runs parent row) cannot turn every single message.delta into a DB round-trip.
        state.last_flush_at = time.monotonic()

    @staticmethod
    def _log_write_anomaly(
        *,
        run_id: str,
        state: _RelayState,
        written: SnapshotUpsertResult,
        submitted_length: int,
    ) -> None:
        """Surface the two SILENT refusal modes of a snapshot upsert. One line per relay each.

        Both outcomes are indistinguishable from a successful flush at the call site, yet each is
        the observable signal behind an open question:

        * not applied → the tenancy guard rejected the write, i.e. this ``run_id`` already belongs
          to another user's snapshot — the evidence needed to settle whether Hermes run ids are
          globally unique (Q-066-2). WARNING: it means the snapshot of this run is not being
          persisted at all.
        * applied but the stored text is shorter than what was submitted → ``result_text`` did not
          advance because the incoming text does not continue the stored one (Q-066-1: replay-from-
          start vs. new-events-only relay semantics). DEBUG: the run keeps working, the snapshot
          simply freezes at its fullest known text; tools/approval/tokens still update.

        Latched per relay so a persistent condition costs one line, not one every few seconds. Only
        ids and LENGTHS are logged — never ``result_text`` or the approval preview (user content,
        ADR-066 §5).
        """
        if not written.applied:
            if not state.tenancy_skip_logged:
                state.tenancy_skip_logged = True
                logger.warning("agent run snapshot upsert skipped (tenancy) run_id=%s", run_id)
            return
        if written.stored_text_length < submitted_length and not state.text_frozen_logged:
            state.text_frozen_logged = True
            logger.debug(
                "agent run snapshot result_text frozen run_id=%s stored=%d submitted=%d",
                run_id,
                written.stored_text_length,
                submitted_length,
            )

    def _build_pending_approval(self, event: _SseEvent) -> dict[str, Any]:
        """Build the ``{tool, preview}`` payload of an ``approval.request`` (ADR-066 §6).

        The event shape is Hermes' external contract, so both carriers are probed defensively; a
        miss yields ``None`` for that field rather than dropping the pending state (the fact that an
        approval is awaited matters more than its label). The preview is bounded by the same
        ``AGENT_STATE_RESULT_TEXT_MAX_CHARS`` cap as the run text — it is user content stored in
        JSONB and must not be unbounded; no separate knob is introduced.
        """
        preview = _extract_approval_preview(event)
        if preview is not None:
            max_chars = self._settings.agent_state_result_text_max_chars
            if len(preview) > max_chars:
                preview = preview[:max_chars]
        return {"tool": _extract_tool_name(event), "preview": preview}

    async def _mark_terminal(self, run_id: str, status: str) -> None:
        """Record a terminal ``agent_runs.status`` (ADR-066 §3) and commit (streaming context).

        Unconditional w.r.t. the billing flag (the lifecycle row now always exists) but CONDITIONAL
        on the run still being active (``WHERE status IN ('running','resumed')``, enforced by the
        repository) so the FIRST terminal status wins and a late event cannot overwrite a
        ``cancelled``/``paused`` that was recorded meanwhile.

        Like :meth:`_flush_snapshot`, a DB failure must not escape the relay generator: it would
        bypass the ``httpx.HTTPError`` handler, surface as a raw error mid-stream and leave the
        session without a rollback. It is logged and rolled back instead — the status simply stays
        as it was, and a re-subscription re-applies the same conditional transition.
        """
        try:
            await self._runs_repo.mark_status(run_id, status)
            await self._session.commit()
        except SQLAlchemyError:
            logger.warning("agent run status write failed run_id=%s status=%s", run_id, status)
            await self._session.rollback()

    async def _pause_run(
        self,
        *,
        user_id: uuid.UUID,
        run_id: str,
        charged: int,
        state: _RelayState,
    ) -> bytes:
        """Stop the run at zero balance, build the synthetic terminal ``run.paused`` (ADR-064 §3).

        NOT a generator: (1) INTERRUPT the Hermes run so no further loop API-calls happen — via
        ``_interrupt_run``, which deliberately does NOT mark the run ``cancelled`` (ADR-066 §3: the
        status belongs to the client ``/stop`` path only, otherwise a credits-exhausted run would
        transiently read as ``stopped`` and ``/resume`` would answer 409); (2) flush the final
        snapshot and persist ``status=paused``/``paused_reason``, committing (streaming context);
        (3) return a self-contained ``run.paused`` SSE block built from the LOCAL relay buffer
        (accumulated message.delta text + collected tool events) — no round-trip to Hermes.
        No debt is created (the last debit was ``charge <= balance``); balance is 0.
        """
        await self._interrupt_run(user_id=user_id, run_id=run_id)
        # Terminal for the client: nothing is awaited from them any more (ADR-066 §6).
        state.pending_approval = None
        await self._flush_snapshot(user_id=user_id, run_id=run_id, state=state, immediate=True)
        await self._runs_repo.mark_paused(run_id, _REASON_CREDITS_EXHAUSTED)
        await self._session.commit()
        payload: dict[str, Any] = {
            "event": _EVENT_RUN_PAUSED,
            "run_id": run_id,
            "reason": _REASON_CREDITS_EXHAUSTED,
            "status": "paused",
            "output": "".join(state.partial_text),
            "steps": state.steps,
            "billed": charged,
            "balance": 0,
            "usage": {
                "cumulative_input_tokens": state.input_tokens,
                "cumulative_output_tokens": state.output_tokens,
            },
        }
        logger.info("agent run paused run_id=%s billed=%d", run_id, charged)
        return f"data: {json.dumps(payload)}\n\n".encode()

    async def _bill_completed(
        self, *, user_id: uuid.UUID, run_id: str, event: _SseEvent, charged: int = 0
    ) -> bool:
        """Finalize a completed run's remainder. Returns True if billing was attempted.

        ADR-064 §2: ``remainder = usage_to_credits(final) - charged`` is debited once with the BARE
        ``run_id`` idempotency key (a separate keyspace from the per-step ``run_id:step`` keys).
        With the flag OFF ``charged == 0`` so ``remainder == usage_to_credits(final)`` — the full
        ADR-047 post-hoc debit, idempotent by ``run_id``. The remainder goes through the ADR-047/
        ADR-051 debt-capable path (meta WITHOUT ``incremental``): usually covered by balance; a debt
        is possible only in a rare race (fallback). Insufficient balance: ``consume`` rolls back its
        savepoint (no orphan row, balance untouched — ADR-047 §6) and the uncharged delta is an
        audit-only ``billing_debit_insufficient`` event; the relay is never broken.

        Billing ONLY — the terminal ``agent_runs.status`` is NOT written here (ADR-066 §3). The
        lifecycle status is recorded by the ``run.completed`` handler in :meth:`stream_events`
        BEFORE this call, so that it never depends on the outcome of a debit: an unexpected billing
        failure (the generic ``except`` below rolls back and swallows) used to leave the run
        ``running`` forever and make ``/state`` lie indefinitely.
        """
        usage = _extract_usage(event)
        input_tokens = _as_int(usage.get("input_tokens"))
        output_tokens = _as_int(usage.get("output_tokens"))
        total_tokens = _as_int(usage.get("total_tokens"))
        model = _extract_model(event)
        owed = usage_to_credits(
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            credits_per_1k_input=self._settings.credits_per_1k_input,
            credits_per_1k_output=self._settings.credits_per_1k_output,
        )
        # ADR-064 §2: only the remainder over what per-step billing already charged.
        amount = owed - charged
        if amount <= 0:
            logger.info(
                "agent run completed, no remainder run_id=%s owed=%d charged=%d",
                run_id,
                owed,
                charged,
            )
            return True

        meta: dict[str, Any] = {
            "source": "agent_run",
            "runId": run_id,
            "usage": {
                "input_tokens": input_tokens,
                "output_tokens": output_tokens,
                "total_tokens": total_tokens,
            },
            "model": model,
        }
        try:
            result = await self._wallet.consume(
                user_id=user_id,
                amount=amount,
                idempotency_key=run_id,
                meta=meta,
            )
        except InsufficientCreditsError:
            # Balance too low for the run's usage. consume already rolled back its savepoint
            # (ADR-047 §6): no debit ledger row, balance untouched, no orphan row. Do NOT break the
            # SSE relay (run already completed upstream). Record the uncharged delta as an audit
            # event — NOT a ledger row — so real usage is not silently lost (reconciliation
            # deferred, Q-047-2 / TD-029). No secrets in payload (runId/usage/model/amount/balance).
            await self._record_insufficient(
                user_id=user_id,
                run_id=run_id,
                amount=amount,
                model=model,
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                total_tokens=total_tokens,
            )
            # Streaming-context persistence (ADR-047 §6): _bill_completed runs INSIDE the
            # StreamingResponse body generator, AFTER FastAPI has already torn down the request
            # session dependency (session_scope yield → commit). So the outer transaction is never
            # committed by the teardown for this path. consume()'s begin_nested() only released a
            # savepoint (savepoint release ≠ transaction commit); the billing_debit_insufficient
            # audit row would be lost. Commit the SAME session that recorded it. Idempotent by
            # runId: a replay re-commits the same (or no) state harmlessly. The chat path is
            # unaffected — it bills in the plain POST handler whose session_scope teardown commits.
            await self._session.commit()
            return True
        except Exception:
            # Never break the SSE relay on a non-insufficient billing failure: the run is already
            # done upstream. Roll back any partial/dirty state so it is not carried into the rest of
            # the stream (no commit — there is nothing to persist on this path). Generic log, no
            # secrets.
            logger.warning("agent run billing failed run_id=%s", run_id)
            await self._session.rollback()
            return True
        # Streaming-context persistence (ADR-047 §6): see the InsufficientCreditsError branch
        # above — _bill_completed runs inside the StreamingResponse body generator, after the
        # session dependency teardown has already committed/closed this request, so the debit
        # savepoint
        # released by consume() (begin_nested) is never committed by the teardown. Commit the SAME
        # session through which consume() INSERTed the debit so the ledger row + billing_debit audit
        # persist. Idempotent by runId (ADR-047 §4): a replayed run.completed hits ON CONFLICT (no
        # new row) and this commit is a harmless no-op.
        await self._session.commit()
        logger.info(
            "agent run billed run_id=%s amount=%d replay=%s",
            run_id,
            amount,
            result.idempotent_replay,
        )
        return True

    async def _record_insufficient(
        self,
        *,
        user_id: uuid.UUID,
        run_id: str,
        amount: int,
        model: str | None,
        input_tokens: int,
        output_tokens: int,
        total_tokens: int,
    ) -> None:
        """Record the uncharged agent-run delta as a ``billing_debit_insufficient`` audit event.

        Audit-only (append-only audit_logs), NOT a ledger row (ADR-047 §6): the financial ledger
        stays clean and reconcilable while the real usage is captured for later reconciliation
        (Q-047-2 / TD-029). Payload carries runId/usage/model/required amount/current balance and no
        secrets (redaction guard in AuditService also enforces this).
        """
        balance = await self._wallet.current_balance(user_id)
        await self._audit.record(
            AuditEvent(
                user_id=user_id,
                event_type=EVENT_BILLING_DEBIT_INSUFFICIENT,
                payload={
                    "runId": run_id,
                    "usage": {
                        "input_tokens": input_tokens,
                        "output_tokens": output_tokens,
                        "total_tokens": total_tokens,
                    },
                    "model": model,
                    "amount": amount,
                    "balance": balance,
                },
            )
        )
        logger.info(
            "agent run billing insufficient run_id=%s amount=%d balance=%d",
            run_id,
            amount,
            balance,
        )

    # --- approval / stop passthrough --------------------------------------------------------

    async def approval(
        self, *, user_id: uuid.UUID, run_id: str, body: dict[str, Any]
    ) -> dict[str, Any]:
        """Passthrough ``POST {base}/v1/runs/{runId}/approval`` (ADR-045 §3).

        ADR-066 §6: AFTER a 2xx passthrough the stored ``pending_approval`` is dropped — the third
        clearing point besides ``tool.*`` and the terminal events. Without it the derived
        ``waiting_approval`` status would stick in ``/state`` after the user already answered.
        Owner-scoped and never INSERTs; a snapshot-less run simply has nothing to clear. Committed
        by the request session_scope teardown (this is a plain handler, not the streaming context).
        """
        result = await self._passthrough_post(user_id, f"/v1/runs/{run_id}/approval", body)
        await self._snapshots_repo.clear_pending_approval(run_id, user_id)
        return result

    async def stop(self, *, user_id: uuid.UUID, run_id: str) -> dict[str, Any]:
        """CLIENT stop path: passthrough ``POST {base}/v1/runs/{runId}/stop`` + ``cancelled``.

        ADR-066 §3: after a 2xx passthrough the run is marked ``cancelled`` — CONDITIONALLY
        (``WHERE status IN ('running','resumed')``), so stopping an already finished/paused run does
        not overwrite its terminal status. This method is the CLIENT path ONLY: the internal
        Hermes interrupt of pause-at-zero goes through :meth:`_interrupt_run`, which performs the
        very same passthrough WITHOUT touching the status (ADR-064 §3) — marking it there would make
        a credits-exhausted run transiently ``cancelled``, so ``/state`` would report ``stopped``
        instead of ``paused`` (no top-up offer in the UI) and ``POST …/resume`` would answer
        ``409 run_not_resumable`` inside that window. Committed by the request session_scope
        teardown (plain handler). ``stop → stopped`` is eventually consistent: Hermes may still be
        flushing buffered events into an open relay at this point.

        The status write is OWNER-SCOPED (``mark_stopped(run_id, user_id)``): ``run_id`` arrives
        straight from the request path and Hermes may answer 2xx for an unknown/foreign run
        (idempotent-stop semantics), so an unscoped UPDATE would let one user cancel another user's
        run. A foreign id updates 0 rows; the passthrough result is still returned (no 403).
        """
        result = await self._interrupt_run(user_id=user_id, run_id=run_id)
        await self._runs_repo.mark_stopped(run_id, user_id)
        return result

    async def _interrupt_run(self, *, user_id: uuid.UUID, run_id: str) -> dict[str, Any]:
        """Interrupt the Hermes run WITHOUT recording any status (ADR-066 §3).

        The transport-level half of :meth:`stop`, shared with the internal pause-at-zero path. Kept
        separate precisely so the ``cancelled`` status can never leak onto the internal path.
        """
        return await self._passthrough_post(user_id, f"/v1/runs/{run_id}/stop", None)

    async def _passthrough_post(
        self, user_id: uuid.UUID, path: str, body: dict[str, Any] | None
    ) -> dict[str, Any]:
        """POST to the user's instance; relay the JSON body. 502 on transport/non-2xx failure."""
        endpoint = await self._manager.ensure_running(user_id)
        url = f"{endpoint.base_url}{path}"
        try:
            async with httpx.AsyncClient(
                timeout=self._settings.hermes_proxy_timeout_seconds
            ) as client:
                response = await client.post(
                    url, json=body, headers=self._bearer_headers(endpoint.api_key)
                )
        except httpx.HTTPError as exc:
            logger.warning("hermes passthrough transport error path=%s", path)
            raise UpstreamError("hermes instance unreachable") from exc
        if not 200 <= response.status_code < 300:
            logger.warning(
                "hermes passthrough non-2xx path=%s status=%s", path, response.status_code
            )
            raise UpstreamError("hermes request failed")
        try:
            data = response.json()
        except ValueError:
            data = {}
        return data if isinstance(data, dict) else {}

    # --- state snapshot (read-only) ---------------------------------------------------------

    async def get_state(self, *, user_id: uuid.UUID, run_id: str) -> RunStateView:
        """``GET /v1/agent/runs/{runId}/state`` — STRICTLY read-only snapshot (ADR-066 §5).

        Invariants, all deliberate:

        * **No ``ensure_running``** — reading the state never wakes a hibernated container, which
          would otherwise cost a cold start (~30-40 s, ADR-056) on every background polling tick.
        * **No call to Hermes at all** — only ``SELECT`` from ``agent_runs`` +
          ``agent_run_snapshots`` (after hibernation Hermes lost its in-memory run registry anyway).
        * **No debit** — reading is free, ``WalletService`` is not involved.
        * **No policy-gate** — a credits block applies to STARTING a generation, not to reading what
          already happened, so ``200 {status:blocked}`` cannot occur on this route.

        Ownership follows the ``/resume`` pattern: a missing row OR a foreign ``user_id`` raises
        :class:`NotFoundError` → 404, never 403 (agent-proxy/06-rbac.md). Runs launched before this
        feature was deployed have no ``agent_runs`` row and therefore also answer 404 (no backfill —
        the source data never existed).

        The snapshot row may be ABSENT while the lifecycle row exists (the relay writer has not
        flushed a single event yet) → 200 with defaults: empty text, no tool, no approval, zero
        usage and ``updated_at`` taken from ``agent_runs``.
        """
        run = await self._runs_repo.get(run_id)
        if run is None or run.user_id != user_id:
            raise NotFoundError("run not found")
        # Owner-scoped read as well (defense-in-depth): the RBAC decision above is already made on
        # agent_runs, but a Hermes run_id colliding across tenants (Q-064-4) must not surface
        # another user's text — a mismatch degrades to the empty-snapshot defaults, never a leak.
        snapshot = await self._snapshots_repo.get(run_id, user_id)
        pending_approval = snapshot.pending_approval if snapshot is not None else None
        status = map_client_status(run.status, has_pending_approval=pending_approval is not None)
        return RunStateView(
            run_id=run.run_id,
            session_id=run.session_id,
            status=status,
            result_text=snapshot.result_text if snapshot is not None else "",
            last_tool=snapshot.last_tool if snapshot is not None else None,
            pending_approval=pending_approval,
            # ADR-066 §5: this carries agent_runs.paused_reason (v1: only 'credits_exhausted') and
            # is NOT the policy blockReason enum of ADR-004 — the value sets do not overlap. Filled
            # only while the run is actually paused.
            block_reason=run.paused_reason if status == "paused" else None,
            input_tokens=snapshot.input_tokens if snapshot is not None else 0,
            output_tokens=snapshot.output_tokens if snapshot is not None else 0,
            # Staleness detector for the client: with no subscriber on /events an active run's
            # snapshot does not move. The retention sweep never shifts it.
            updated_at=snapshot.updated_at if snapshot is not None else run.updated_at,
            continued_from=run.continued_from_run_id,
        )

    # --- resume (continuation) --------------------------------------------------------------

    async def resume(
        self, *, user_id: uuid.UUID, run_id: str, message: str | None
    ) -> RunResumeResult:
        """Resume a paused run as a continuation in the same Hermes session (ADR-064 §5).

        Order (ADR-064 §5): RBAC-404 → status pre-guard (409 run_not_resumable) → policy-gate
        (200 blocked if still no credits/debt) → atomic CAS ``paused→resumed`` (the single race
        arbiter) → ensure_running → hydrate transcript → launch a NEW run in the SAME session →
        chain-insert the child (continued_from = runId) → 202 {runId: new, continuedFrom: runId}.
        The CAS loser resolves idempotently to the existing child (202) or 409 resume_in_progress.
        A launch failure AFTER a won CAS reverts ``resumed→paused`` (run stays resumable) → 502.
        """
        # (2) RBAC: a foreign / unknown run is invisible → 404 (ADR-064 §5 step 2).
        run = await self._runs_repo.get(run_id)
        if run is None or run.user_id != user_id:
            raise NotFoundError("run not found")
        # (3) Informational status pre-guard; the authoritative arbiter is the CAS (step 5).
        if run.status not in ("paused", "resumed"):
            raise RunNotResumableError("run is not resumable")

        # (4) Policy-gate (read-only, BEFORE any status change): if the balance is still 0 / in debt
        # after a would-be top-up, resume does NOT flip status or launch — 200 blocked (ADR-004).
        blocked = await self._resume_policy_block(user_id)
        if blocked is not None:
            return blocked

        # (5) Atomic CAS paused→resumed — the single serializing step (own short transaction).
        cas = await self._runs_repo.cas_resume(run_id)
        if cas is None:
            # Lost the CAS (already resumed / retry): resolve to the existing child idempotently.
            child = await self._runs_repo.active_child(run_id)
            if child is not None:
                return RunResumeResult(blocked=False, run_id=child.run_id, continued_from=run_id)
            # Narrow window between the winner's CAS and its chain-insert → client retries.
            raise ResumeInProgressError("resume in progress")
        session_id = str(cas.session_id)
        model = cas.model
        # Commit the CAS immediately to release the row lock (short transaction, ADR-064 §5).
        await self._session.commit()

        # (6-9) Only the CAS winner launches. On any failure BEFORE a child is chained, revert
        # resumed→paused (guarded by NOT EXISTS child) so the run stays resumable, then surface the
        # error (502 for upstream, 409 for an expired session). A launched-but-unchained run is an
        # orphan handled by the idle-reaper (Q-064-1).
        try:
            endpoint = await self._manager.ensure_running(user_id)
            history = await self._fetch_session_transcript(endpoint, session_id)
            hermes_body: dict[str, Any] = {"session_id": session_id}
            if message is not None:
                hermes_body["input"] = message
            if model is not None:
                hermes_body["model"] = model
            if history:
                hermes_body["conversation_history"] = history
            new_run_id, status = await self._launch_run(endpoint, hermes_body)
        except Exception:
            await self._runs_repo.revert_cas(run_id)
            await self._session.commit()
            raise

        # (9) Chain-insert the continuation child (runId is already 'resumed' from the CAS).
        await self._runs_repo.create_running(
            new_run_id,
            user_id,
            session_id,
            model,
            continued_from_run_id=run_id,
            status="running",
        )
        await self._session.commit()
        await self._audit.record(
            AuditEvent(
                user_id=user_id,
                event_type=EVENT_AGENT_RUN,
                payload={
                    "phase": "resumed",
                    "runId": new_run_id,
                    "continuedFrom": run_id,
                    "status": status,
                },
            )
        )
        return RunResumeResult(blocked=False, run_id=new_run_id, continued_from=run_id)

    async def _resume_policy_block(self, user_id: uuid.UUID) -> RunResumeResult | None:
        """Re-evaluate the credits policy-gate for resume (ADR-064 §5 step 4). None = allowed.

        Same achievable block set as ``run()`` (credits branch + the ADR-051 debt gate). Read-only:
        no status flip, no launch, no debit. Returns a blocked RunResumeResult (200) or None.
        """
        state = await load_policy_state(self._session, user_id)
        decision: Decision = evaluate(state, Mode.credits)
        if not decision.allow:
            reason = decision.block_reason.value if decision.block_reason is not None else None
            await self._audit.record(
                AuditEvent(
                    user_id=user_id,
                    event_type=EVENT_AGENT_RUN,
                    payload={"phase": "resumed", "blockReason": reason},
                )
            )
            if reason not in _AGENT_BLOCK_REASONS:
                logger.warning("agent resume blocked with unexpected reason=%s", reason)
            return RunResumeResult(blocked=True, block_reason=reason)
        if self._settings.agent_debt_reconcile_enabled:
            debt = await self._wallet.current_debt(user_id)
            if debt > 0:
                await self._audit.record(
                    AuditEvent(
                        user_id=user_id,
                        event_type=EVENT_AGENT_RUN,
                        payload={
                            "phase": "resumed",
                            "blockReason": _DEBT_OUTSTANDING,
                            "debt": debt,
                        },
                    )
                )
                return RunResumeResult(blocked=True, block_reason=_DEBT_OUTSTANDING)
        return None

    async def _fetch_session_transcript(
        self, endpoint: InstanceEndpoint, session_id: str
    ) -> list[dict[str, Any]]:
        """Hydrate the Hermes session transcript into ``conversation_history`` (ADR-064 §7).

        ``GET {base}/api/sessions/{session_id}/messages`` (Bearer) → ``[{role, content}]``. The
        exact response shape is pending the Hermes image patch (Q-064-3); the mapping is defensive:
        ``messages``/``data`` list envelope or a bare list, keeping only items with ``role`` +
        ``content``. A 404 or an EMPTY history → the session cannot be continued → 409
        ``session_expired`` (caller reverts the CAS). Transport failure → 502.
        """
        url = f"{endpoint.base_url}/api/sessions/{session_id}/messages"
        try:
            async with httpx.AsyncClient(
                timeout=self._settings.hermes_proxy_timeout_seconds
            ) as client:
                response = await client.get(url, headers=self._bearer_headers(endpoint.api_key))
        except httpx.HTTPError as exc:
            logger.warning("hermes session transcript transport error")
            raise UpstreamError("hermes session transcript unreachable") from exc
        if response.status_code == 404:
            raise SessionExpiredError("session transcript not found")
        if not 200 <= response.status_code < 300:
            logger.warning("hermes session transcript non-2xx status=%s", response.status_code)
            raise UpstreamError("hermes session transcript failed")
        try:
            payload = response.json()
        except ValueError as exc:
            raise UpstreamError("hermes session transcript invalid body") from exc
        raw_messages: Any = payload
        if isinstance(payload, dict):
            raw_messages = payload.get("messages") or payload.get("data") or []
        if not isinstance(raw_messages, list):
            raw_messages = []
        history: list[dict[str, Any]] = [
            {"role": item["role"], "content": item["content"]}
            for item in raw_messages
            if isinstance(item, dict) and "role" in item and "content" in item
        ]
        if not history:
            raise SessionExpiredError("session transcript empty")
        return history

    @staticmethod
    def _bearer_headers(api_key: str) -> dict[str, str]:
        """Authorization header for the instance. Never logged (redaction `*authorization*`)."""
        return {"Authorization": f"Bearer {api_key}"}


@dataclass(frozen=True)
class _SseEvent:
    """A parsed SSE block: the optional ``event:`` name and the decoded ``data:`` JSON (if any)."""

    name: str | None
    data: dict[str, Any]


async def _iter_sse_blocks(
    response: httpx.Response,
) -> AsyncIterator[tuple[_SseEvent, bytes]]:
    """Yield (parsed_event, raw_block_bytes) for each SSE block of the stream.

    Splits on the blank-line block separator. The raw bytes (including the trailing ``\\n\\n``) are
    forwarded to the client verbatim so relaying never mutates the wire format; the parsed event is
    used only to detect terminal billing events. Malformed/partial blocks are forwarded raw with an
    empty parsed payload (the relay must not drop bytes on a parse miss).
    """
    buffer = b""
    async for chunk in response.aiter_bytes():
        buffer += chunk
        while b"\n\n" in buffer:
            block, buffer = buffer.split(b"\n\n", 1)
            raw = block + b"\n\n"
            yield _parse_sse_block(block), raw
    if buffer.strip():
        # Trailing block without a terminating blank line (stream closed): forward + parse.
        yield _parse_sse_block(buffer), buffer


def _parse_sse_block(block: bytes) -> _SseEvent:
    """Parse a single SSE block into an :class:`_SseEvent` (name + data JSON). Never raises."""
    name: str | None = None
    data_lines: list[str] = []
    for line_bytes in block.split(b"\n"):
        try:
            line = line_bytes.decode("utf-8")
        except UnicodeDecodeError:
            continue
        if line.startswith(":"):
            continue  # SSE comment / keepalive
        if line.startswith("event:"):
            name = line[len("event:") :].strip()
        elif line.startswith("data:"):
            data_lines.append(line[len("data:") :].strip())
    data: dict[str, Any] = {}
    if data_lines:
        try:
            parsed = json.loads("\n".join(data_lines))
            if isinstance(parsed, dict):
                data = parsed
        except ValueError:
            data = {}
    return _SseEvent(name=name, data=data)


def _event_name(event: _SseEvent) -> str | None:
    """Resolve the event name from the SSE ``event:`` field or a ``type``/``event`` data field."""
    if event.name:
        return event.name
    for key in ("type", "event"):
        value = event.data.get(key)
        if isinstance(value, str):
            return value
    return None


def _extract_tool_name(event: _SseEvent) -> str | None:
    """Tool name of a ``tool.*`` / ``approval.request`` block (ADR-066 §6). Best-effort.

    The payload shape is Hermes' external contract (``{tool, ...}`` per agent-proxy/05-events.md);
    the common aliases are probed defensively so an upstream rename degrades to ``None`` instead of
    breaking the relay.
    """
    for key in ("tool", "tool_name", "name"):
        value = event.data.get(key)
        if isinstance(value, str) and value:
            return value
    return None


def _extract_approval_preview(event: _SseEvent) -> str | None:
    """Human-readable preview of what an ``approval.request`` is asking to approve (§6).

    Only string carriers are accepted — a structured payload is not serialised into the snapshot
    (the preview is a UI label, not a transcript; the full event is always available via /events).
    """
    for key in ("preview", "description", "summary"):
        value = event.data.get(key)
        if isinstance(value, str) and value:
            return value
    return None


def _extract_usage(event: _SseEvent) -> dict[str, Any]:
    usage = event.data.get("usage")
    return usage if isinstance(usage, dict) else {}


def _extract_delta_text(event: _SseEvent) -> str:
    """Best-effort assistant text of a ``message.delta`` block for the run.paused buffer (§3).

    The exact Hermes shape is relayed as-is (external contract); this local buffer probes the common
    carriers (``text`` / ``delta.text`` / ``content``) defensively — a miss just yields ``""`` (the
    paused body is a convenience snapshot, not an authoritative transcript; hydrate is the source).
    """
    data = event.data
    value = data.get("text")
    if isinstance(value, str):
        return value
    delta = data.get("delta")
    if isinstance(delta, dict) and isinstance(delta.get("text"), str):
        return str(delta["text"])
    content = data.get("content")
    if isinstance(content, str):
        return content
    return ""


def _extract_model(event: _SseEvent) -> str | None:
    model = event.data.get("model")
    return model if isinstance(model, str) else None


def _as_int(value: Any) -> int:
    """Coerce a usage token count to int; non-int/missing → 0 (robust vs upstream drift)."""
    if isinstance(value, bool):
        return 0
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    return 0
