"""Renders the instance ``config.yaml`` (toolset restriction + LLM model section, ADR-046/ADR-055).

Written into the user's volume before the container boots so the instance starts with:
- a SAFE toolset only: ``platform_toolsets.api_server`` = ``HERMES_DEFAULT_TOOLSET`` (default
  ``[web, file, vision, skills, todo]``) — never ``terminal``/``browser``/``code_execution``/
  ``computer_use`` (RCE / arbitrary-code surface, 05-security.md); ``approvals.mode: deny`` (deny
  dangerous actions without explicit approval). Neither is weakened by ADR-055.
- an explicit ``model`` section (ADR-055): ``model.default = "<provider>/<model>"`` and
  ``model.provider = "<provider>"`` (CONCRETE provider, never ``auto`` — auto defaults to the
  openrouter base_url → 401), plus an optional ``model.base_url`` (custom/azure-foundry/lmstudio).
  Without this section the image falls back to its built-in default (openrouter) → 401.

Hand-rendered (no YAML lib dependency) for a small, fixed, fully-controlled output. All injected
values (toolset names, provider, model, base_url) are validated to conservative charsets so a
malformed config value cannot inject YAML structure; an invalid value fails fast (raises) rather
than emitting broken/injected YAML.
"""

from __future__ import annotations

import re

from app.config import (
    HERMES_INSTANCE_LLM_KEY_ENV,
    HERMES_PROVIDER_ALLOWLIST,
    HERMES_PROVIDERS_CONFIG_API_KEY,
)
from app.errors import UpstreamError

# Conservative allowlisted shape for a toolset name (letters/digits/_/-). Anything else is dropped
# so a malformed HERMES_DEFAULT_TOOLSET value cannot break out of the YAML list item.
_TOOLSET_NAME_RE = re.compile(r"^[A-Za-z0-9_-]+$")

# ADR-055 §1: conservative charsets for the model section values (anti YAML-injection).
# model id: letters/digits and . _ / - (dot/slash for provider/model ids and `-latest` suffixes).
_MODEL_NAME_RE = re.compile(r"^[A-Za-z0-9._/\-]+$")
# base_url: an http(s) URL over a conservative charset (no spaces/quotes/newlines).
_BASE_URL_RE = re.compile(r"^https?://[A-Za-z0-9._:/\-]+$")

# Headless approval mode: deny dangerous actions unless explicitly approved (ADR-046 §6). The
# restricted toolset already excludes the dangerous tools; this is defence in depth.
_APPROVALS_MODE = "deny"


def render_instance_config(
    *,
    toolset: list[str],
    provider: str,
    model: str,
    base_url: str = "",
    api_key: str = "",
) -> str:
    """Render the instance ``config.yaml`` body (toolset + model section, ADR-046/ADR-055).

    Invalid/empty toolset entries are dropped; if nothing valid remains, the safe default set is
    used so the instance never boots with an unrestricted toolset. The ``model`` section is always
    emitted: ``default="<provider>/<model>"`` and ``provider="<provider>"`` (concrete); a
    ``base_url`` line is emitted ONLY when ``base_url`` is non-empty. Deterministic output (stable
    order) so it is testable.

    ADR-055 §6 (config-api-key providers, e.g. ``custom``): when ``provider`` is in
    ``HERMES_PROVIDERS_CONFIG_API_KEY`` an ``api_key`` line is emitted as a FIXED env-REF constant
    ``"${HERMES_INSTANCE_LLM_KEY}"`` — the image expands it from the container env at load time. The
    secret KEY VALUE is NEVER written to the volume file (only the env-ref literal), so a YAML
    injection via the key content is structurally impossible. ``api_key`` is accepted to express the
    contract and gate emission on the key being present; its value is not inlined and never logged.
    For env-key providers no ``api_key`` line is emitted (the key flows via ``<PROVIDER>_API_KEY``).

    Raises :class:`UpstreamError` (fail-fast, before the container is created) when ``provider`` is
    not in the allowlist, ``model`` is empty or has an unsafe charset, or ``base_url`` is non-empty
    but malformed — so a bad value never reaches the rendered YAML.
    """
    safe = [name for name in toolset if _TOOLSET_NAME_RE.match(name)]
    if not safe:
        safe = ["web", "file", "vision", "skills", "todo"]

    provider = provider.strip()
    model = model.strip()
    base_url = base_url.strip()
    if provider not in HERMES_PROVIDER_ALLOWLIST:
        raise UpstreamError(
            f"hermes runtime is not configured (HERMES_LLM_PROVIDER={provider!r} invalid)"
        )
    if not model or not _MODEL_NAME_RE.match(model):
        raise UpstreamError(
            f"hermes runtime is not configured (HERMES_MODEL={model!r} empty or unsafe)"
        )
    if base_url and not _BASE_URL_RE.match(base_url):
        raise UpstreamError(
            f"hermes runtime is not configured (HERMES_LLM_BASE_URL={base_url!r} unsafe)"
        )

    lines = [
        "# Generated by control plane (ADR-046/ADR-055). Restricts toolset + pins the LLM model.",
        "platform_toolsets:",
        "  api_server:",
    ]
    lines.extend(f"    - {name}" for name in safe)
    lines.append("approvals:")
    lines.append(f"  mode: {_APPROVALS_MODE}")
    lines.append("model:")
    lines.append(f'  default: "{provider}/{model}"')
    lines.append(f'  provider: "{provider}"')
    if base_url:
        lines.append(f'  base_url: "{base_url}"')
    if provider in HERMES_PROVIDERS_CONFIG_API_KEY:
        # ADR-055 §6: env-REF constant, not the key value (secret stays in env, never on disk).
        # api_key must be present (the caller supplies HERMES_LLM_API_KEY); empty → fail-fast (a
        # config-api-key provider with no key would 401 at runtime).
        if not api_key.strip():
            raise UpstreamError(
                f"hermes runtime is not configured (HERMES_LLM_API_KEY required for "
                f"provider {provider!r})"
            )
        lines.append(f'  api_key: "${{{HERMES_INSTANCE_LLM_KEY_ENV}}}"')
    lines.append("")
    return "\n".join(lines)
